project:
  type: website
  output-dir: docs

website:
  title: "Bella Kormos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About me
      - href: posts.qmd # add blog post for projects
        text: Projects
      - href: interests.qmd
        text: Interests
      - href: cv.qmd
        text: Resume
      - href: research.qmd
        text: Research experience 
       

format:
  html:
    theme : styles.scss # Apply styles.scss file to theme
    mainfont: "EB Garamond"
    page-layout: full
    toc: true

editor: visual

